# Generated by Django 3.2.6 on 2022-02-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hawaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pho_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hawaapp.phone'),
        ),
    ]
