# Generated by Django 3.2.6 on 2022-02-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawaapp', '0002_alter_hawauser_per_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hawauser',
            name='birthdate',
            field=models.DateField(max_length=500, null=True),
        ),
    ]
